# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97d2f1d4be767c39d702e476e331c7f37ee4825aee9719052839e1d070c0eaa06201ac4d742afe3ceb06db65c18ab39abac23058c120781640699934c919d685
SECRET_KEY: sk_test_RV8FScIYSOXRrbCxv4m8BY0A
PUBLISHABLE_KEY: pk_test_9YU1q0qZB5sa3xFYDPsfri9G

stripe_api_key: sk_test_RV8FScIYSOXRrbCxv4m8BY0A
stripe_publishable_key: pk_test_9YU1q0qZB5sa3xFYDPsfri9G

stripeToken: pk_test_9YU1q0qZB5sa3xFYDPsfri9G
  stripeEmail: tashby2714@gmail.com


test:
  secret_key_base: 867e847dbbf903942c31acfafbd4dd9f37215953b0638fde6030626ccca855a8e83bbef4a605e37517004839de44752b93080dca1180311fb066018286c132e6
SECRET_KEY: sk_test_RV8FScIYSOXRrbCxv4m8BY0A
PUBLISHABLE_KEY: pk_test_9YU1q0qZB5sa3xFYDPsfri9G

stripe_api_key: sk_test_RV8FScIYSOXRrbCxv4m8BY0A
stripe_publishable_key: pk_test_9YU1q0qZB5sa3xFYDPsfri9G

stripeToken: pk_test_9YU1q0qZB5sa3xFYDPsfri9G
  stripeEmail: tashby2714@gmail.com

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
